name: skill_spring
description: "A comprehensive Flutter mobile application for college and university students to learn coding languages through free courses, hands-on projects, and interactive materials."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6

  # State Management
  provider: ^6.1.1

  # Navigation
  go_router: ^17.1.0

  # UI & Design
  google_fonts: ^8.0.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  lottie: ^3.0.0

  # Media
  # video_player: ^2.8.2
  # chewie: ^1.7.5
  # flutter_pdfview: ^1.3.2

  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.2.3
  share_plus: ^12.0.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

  # Icons
  cupertino_icons: ^1.0.6

  # Animations & Effects
  animate_do: ^4.2.0
  glassmorphism: ^3.0.0
  flutter_dotenv: ^6.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/certificates/
